/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx_hal.h"
#include "uart.h"

void SysTick_Handler(void) {
	HAL_IncTick();
}

extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;

void USART2_IRQHandler(void) {
	HAL_UART_IRQHandler(&huart2);
}

void USART1_IRQHandler(void) {
	HAL_UART_IRQHandler(&huart1);
}

int main(void) {
	HAL_Init();

	uart2_init();
	uart1_init();

	uart_start_rx_it(&huart2);
	uart_start_rx_it(&huart1);

	while (1) {

	}
}
