/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32l476xx.h"
#include "stm32l476xx_gpio.h"
#include "stm32l476xx_adc.h"

void delay(void) {
	for (volatile uint32_t i = 0; i < 200000; i++)
		;
}

void ADC_GPIO_Init(void) {
	GPIO_Handle_t adcPin;

	adcPin.pGPIOx = GPIOA;

	adcPin.GPIO_PinConfig.GPIO_PinNumber = 0;
	adcPin.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ANALOG;
	adcPin.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&adcPin);
}

volatile uint16_t adcVal;

int main(void) {
	ADC_GPIO_Init();

	ADC_Init();

	while (1) {
		adcVal = ADC_Read();

		delay();
	}
}
