/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stm32f4xx_hal.h>

/*const uint32_t MSIRangeTable[] = { 100000, 200000, 400000, 800000, 1000000,
		2000000, 4000000, 8000000, 16000000, 24000000, 32000000, 48000000 };*/

void SysTick_Handler() {
	HAL_IncTick();
}


UART_HandleTypeDef huart2;

void uart_init() {

	GPIO_InitTypeDef GPIO_Init_Struct = { 0 };

	__HAL_RCC_GPIOA_CLK_ENABLE();

	__HAL_RCC_USART2_CLK_ENABLE();

	GPIO_Init_Struct.Pin = GPIO_PIN_2 | GPIO_PIN_3;
	GPIO_Init_Struct.Mode = GPIO_MODE_AF_PP;
	GPIO_Init_Struct.Alternate = GPIO_AF7_USART2;
	GPIO_Init_Struct.Pull = GPIO_NOPULL;
	GPIO_Init_Struct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;

	HAL_GPIO_Init(GPIOA, &GPIO_Init_Struct);

	huart2.Instance = USART2;
	huart2.Init.BaudRate = 115200;
	huart2.Init.WordLength = UART_WORDLENGTH_8B;
	huart2.Init.StopBits = UART_STOPBITS_1;
	huart2.Init.Parity = UART_PARITY_NONE;
	huart2.Init.Mode = UART_MODE_TX;
	huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
	huart2.Init.OverSampling = UART_OVERSAMPLING_16;

	HAL_UART_Init(&huart2);

}

char *msg = "Hello World..!\r\n";

int main(void) {
	HAL_Init();
	uart_init();

	__HAL_RCC_GPIOA_CLK_ENABLE();
	    GPIOA->MODER &= ~(3 << (5*2));
	    GPIOA->MODER |=  (1 << (5*2));

	/* Loop forever */
	while (1) {

		GPIOA->ODR ^= (1 << 5);

		HAL_UART_Transmit(&huart2, (uint8_t*) msg, 17, 100);
		HAL_Delay(500);

	}
}
