/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32l4xx_hal.h>
#include "uart.h"
#include "spi.h"

const uint32_t MSIRangeTable[] = { 100000, 200000, 400000, 800000, 1000000,
		2000000, 4000000, 8000000, 16000000, 24000000, 32000000, 48000000 };

void SysTick_Handler() {
	HAL_IncTick();
}

void SystemClock_Config(void) {
	RCC_OscInitTypeDef osc = { 0 };
	RCC_ClkInitTypeDef clk = { 0 };

	osc.OscillatorType = RCC_OSCILLATORTYPE_MSI;
	osc.MSIState = RCC_MSI_ON;
	osc.MSIClockRange = RCC_MSIRANGE_8;
	osc.PLL.PLLState = RCC_PLL_NONE;

	HAL_RCC_OscConfig(&osc);

	clk.ClockType = RCC_CLOCKTYPE_SYSCLK |
	RCC_CLOCKTYPE_HCLK |
	RCC_CLOCKTYPE_PCLK1 |
	RCC_CLOCKTYPE_PCLK2;

	clk.SYSCLKSource = RCC_SYSCLKSOURCE_MSI;
	clk.AHBCLKDivider = RCC_SYSCLK_DIV1;
	clk.APB1CLKDivider = RCC_HCLK_DIV1;
	clk.APB2CLKDivider = RCC_HCLK_DIV1;

	HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_0);
}

// DMA IRQ
void DMA1_Channel6_IRQHandler(void) {
	HAL_DMA_IRQHandler(huart2.hdmarx);
}

// UART IRQ
void USART2_IRQHandler(void) {
	HAL_UART_IRQHandler(&huart2);

	// IDLE detection
	if (__HAL_UART_GET_FLAG(&huart2, UART_FLAG_IDLE)) {
		__HAL_UART_CLEAR_IDLEFLAG(&huart2);

		uart_process_data();   // ⭐ process received data
	}
}

uint8_t tx_data = 'A';
uint8_t rx_data;

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    uart_init();
    spi_init();

    while (1)
    {
        HAL_SPI_TransmitReceive(&hspi1, &tx_data, &rx_data, 1, 100);

        printf("Received: %c\r\n", rx_data);

        HAL_Delay(1000);
    }
}
