/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32l476xx.h"
#include "stm32l476xx_gpio.h"

#define GPIO_PIN_5   5
#define GPIO_PIN_13  13

void delay(void)
{
    for (volatile uint32_t i = 0; i < 200000; i++);
}

int main(void)
{
    GPIO_Handle_t GpioLed, GpioBtn;

    /* -------- LED CONFIG (PA5) -------- */
    GpioLed.pGPIOx = GPIOA;
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
    GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

    GPIO_Init(&GpioLed);

    /* -------- BUTTON CONFIG (PC13) -------- */
    GpioBtn.pGPIOx = GPIOC;
    GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
    GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT;
    GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
    GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    GPIO_Init(&GpioBtn);

    /* -------- MAIN LOOP -------- */
    while (1)
    {
        if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_13) == 0) // button pressed
        {
            delay();
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_5);

            while (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_13) == 0);
        }
    }
}
